name: deploy to lambda
on:
  push:
    branches:
      - main  # Replace with the branch you want to trigger the deployment

jobs:
  deploy_source:
    name: build and deploy lambda
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11  # Choose the Python version you need

      - name: Install dependencies
        run: pip install -r requirements.txt  # Replace with the command to install your Python dependencies

      - name: Zip Lambda function
        run: zip -qq -r ./bundle.zip .

      - name: Deploy to Lambda
        run: |
          docker run -v "$PWD":/var/task lambci/lambda:build-python3.8 /var/task/deploy.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-north-1  # Replace with your AWS region
          AWS_FUNCTION_NAME: lambda-functions  # Replace with your Lambda function name
